/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sewa_Villa;

/**
 *
 * @author Dzuna
 */

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

public class GUI_Villa extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    public GUI_Villa() {
        initComponents();
        DefaultTableModel dataModel = (DefaultTableModel) table_data_villa.getModel();
        int rowCount = dataModel.getRowCount();
        while (rowCount > 0) {
            dataModel.removeRow(rowCount -1);
            rowCount = dataModel.getRowCount();
        }
    }
    
    public void clear() {
        txtDurasisewa.setText("");
        memoVilla.setText("");
        btnGroupTipe.clearSelection();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipe = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        radiobtnKecil = new javax.swing.JRadioButton();
        radiobtnSedang = new javax.swing.JRadioButton();
        radiobtnBesar = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoVilla = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtDurasisewa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSewa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_data_villa = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Tipe Villa");

        btnGroupTipe.add(radiobtnKecil);
        radiobtnKecil.setText("Villa Kecil");
        radiobtnKecil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnKecilActionPerformed(evt);
            }
        });

        btnGroupTipe.add(radiobtnSedang);
        radiobtnSedang.setText("Villa Sedang");
        radiobtnSedang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnSedangActionPerformed(evt);
            }
        });

        btnGroupTipe.add(radiobtnBesar);
        radiobtnBesar.setText("Villa Besar");
        radiobtnBesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnBesarActionPerformed(evt);
            }
        });

        memoVilla.setColumns(20);
        memoVilla.setRows(5);
        jScrollPane1.setViewportView(memoVilla);

        jLabel6.setText("Durasi Sewa");

        txtDurasisewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurasisewaActionPerformed(evt);
            }
        });

        jLabel7.setText("Informasi Villa");

        btnSewa.setText("Sewa");
        btnSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSewaActionPerformed(evt);
            }
        });

        jLabel5.setText("Detail Penyewaan");

        jLabel8.setText("Detail Villa ");

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        table_data_villa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipe Villa", "Kode Villa", "Harga Sewa", "Durasi Sewa", "Total Biaya"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(table_data_villa);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiobtnSedang)
                                    .addComponent(radiobtnKecil)
                                    .addComponent(radiobtnBesar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSewa)
                                    .addComponent(txtDurasisewa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBatal)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnKeluar))
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(338, 338, 338))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(335, 335, 335))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radiobtnKecil)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiobtnSedang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiobtnBesar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDurasisewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(btnSewa))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal)
                    .addComponent(btnKeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void radiobtnKecilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnKecilActionPerformed
        // Menampilkan detail villa:
        Villa villa = Villa.villaKecil;
        String detailVilla = villa.getDetailVilla();
        memoVilla.setText(detailVilla);
    }//GEN-LAST:event_radiobtnKecilActionPerformed

    private void txtDurasisewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurasisewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasisewaActionPerformed

    private void btnSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSewaActionPerformed
        JOptionPane.showMessageDialog(null, "Data anda Ditambahkan Ke tabel");
        DefaultTableModel dataModel = (DefaultTableModel) table_data_villa.getModel();
        List list = new ArrayList<>();
        table_data_villa.setAutoCreateColumnsFromModel(true);
        
        // Ambil input dari komponen-komponen antarmuka pengguna
        double harga = 0;
        Villa villa = null;
        String Tipe = null;
        String kodeVilla = "";  // Inisialisasi tipe villa
        
        String tipevila = "";
        if (radiobtnKecil.isSelected()) {
            tipevila = "VK";
        } else if (radiobtnSedang.isSelected()) {
            tipevila = "VS";
        } else if (radiobtnBesar.isSelected()) {
            tipevila = "VB";
        }
        
        if (tipevila.equals("VK")) {
            villa = Villa.villaKecil;
            harga = villa.hargaSewaPerMalam;
            Tipe = Villa.villaKecil.tipe = "Villa Kecil";
        } else if (tipevila.equals("VS")) {
            villa = Villa.villaSedang;
            harga = villa.hargaSewaPerMalam;
            Tipe = Villa.villaSedang.tipe = "Villa Sedang";
        } else if (tipevila.equals("VB")) {
            villa = Villa.villaBesar;
            harga = villa.hargaSewaPerMalam;
            Tipe = Villa.villaBesar.tipe = "Villa Besar";
        }  

        // Hitung total biaya
        int durasi = Integer.parseInt(txtDurasisewa.getText());
        double totalBiaya = harga * durasi;
        DecimalFormat decimalFormat = new DecimalFormat("###,###,##0.00");
        String totalBiayaStr = decimalFormat.format(totalBiaya);

        list.add(Tipe);
        list.add(tipevila);
        list.add(harga);
        list.add(durasi);
        list.add(totalBiayaStr);
        dataModel.addRow(list.toArray());
        clear();
    }//GEN-LAST:event_btnSewaActionPerformed

    private void radiobtnSedangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnSedangActionPerformed
        // Menampilkan detail villa:
        Villa villa = Villa.villaSedang;
        String detailVilla = villa.getDetailVilla();
        memoVilla.setText(detailVilla);
    }//GEN-LAST:event_radiobtnSedangActionPerformed

    private void radiobtnBesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnBesarActionPerformed
        // Menampilkan detail villa:
        Villa villa = Villa.villaBesar;
        Villa.villaBesar.tipe = "Mewah"; // mengubah nilai tipe
        String detailVilla = villa.getDetailVilla();
        memoVilla.setText(detailVilla);
    }//GEN-LAST:event_radiobtnBesarActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        clear();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        DefaultTableModel dataModel = (DefaultTableModel) table_data_villa.getModel();
        int rowCount = dataModel.getRowCount();
        while (rowCount > 0) {
            dataModel.removeRow(rowCount -1);
            rowCount = dataModel.getRowCount();}
    }//GEN-LAST:event_btnHapusActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Villa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Villa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Villa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Villa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Villa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.ButtonGroup btnGroupTipe;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSewa;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea memoVilla;
    private javax.swing.JRadioButton radiobtnBesar;
    private javax.swing.JRadioButton radiobtnKecil;
    private javax.swing.JRadioButton radiobtnSedang;
    private javax.swing.JTable table_data_villa;
    private javax.swing.JTextField txtDurasisewa;
    // End of variables declaration//GEN-END:variables
}
